import { StyleSheet, Dimensions } from "react-native";
import { RecipeCard } from "../../AppStyles";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#000000",
    flexGrow: 1,
  },
  scrollViewStyle: {
    flex: 1,
    backgroundColor: "#000000",
  },
  coupaLogo: {
    height: "100%",
    //height: Dimensions.height,
    width: Dimensions.width,
  },
  coupaContainer: {
    //borderColor: "red",
    //borderWidth: 2,
    //marginVertical: "1%",
    //padding: "1%",
    marginTop: "4%",
    width: "75%",
    height: "10%",
  },
  selectedLocationText: {
    color: "#FAEE89",
    fontWeight: "600",
    //paddingTop: "5%",
  },

  dropdownContainer: {
    marginTop: "20%",
    backgroundColor: "white",
    padding: 12,
    //borderRadius: 5,
    //shadowOpacity: 0.25,
    //shadowRadius: 3,
    //elevation: 5,
    width: "70%",
    alignSelf: "center",
  },
  dropdownItem: {
    padding: 10,
  },
  dropdownText: {
    fontSize: 16,
  },
  recommendationContainer: {
    //padding: 10,
    alignItems: "center",
    backgroundColor: "#000000",
    borderRadius: 20,
    borderColor: "#FAEE89",
    borderWidth: 2.5,
    marginTop: "4%",
    margin: 10,
    height: "38%",
    width: "90%",
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  recBottomContainer: {
    marginTop: "3%",
    width: "100%",
    height: "68%",
    backgroundColor: "gray",
  },
  recImage: {
    justifyContent: "flex-end",
    alignItems: "flex-end",
    width: "100%",
  },
  favNameText: {
    marginTop: "2%",
    fontWeight: "bold",
    color: "#000000",
  },
  favoriteItemContainer: {
    //padding: 10,
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 20,
    margin: 10,
    //borderColor: "black",
    borderWidth: 1,
    width: "45%",
    height: "90%",
    overflow: "hidden",
    borderColor: "#FAEE89",
    borderWidth: 1,
    //alignSelf: "left",
  },
  favText: {
    marginBottom: "4%",
    alignSelf: "flex-start",
    marginLeft: "5%",
    //color: "#FFFFFF",
    color: "#FAEE89",
    fontWeight: "600",
    //fontFamily: "Sora-Regular",
  },
  favContainerInner: {
    //borderWidth: 2,
    width: "100%",
    height: "80%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  favImageBg: {
    width: "100%",
    height: "90%",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    marginTop: "2%",
    //flex: 4,
  },
  favouriteItemBigContainer: {
    alignItems: "center",
    backgroundColor: "#000000",
    borderRadius: 20,
    //margin: 10,
    marginTop: "4%",
    height: "38%",
    width: "90%",
    justifyContent: "flex-end",
    borderColor: "#FAEE89",
    borderWidth: 1.5,
    //flexDirection: "row",
    marginBottom: "5%",
  },
  locationText: {
    color: "#DDD",
    marginBottom: "5%",
    marginRight: "2%",
  },
  headingText: {
    fontWeight: "bold",
    fontSize: 17,
    marginBottom: "1%",
    marginTop: "1.5%",
    //color: "#FFF",
    color: "#FAEE89",
  },
  headingTopLeft: {
    fontWeight: "600",
    fontSize: 12,
    marginBottom: "1%",
    alignSelf: "flex-start",
    marginTop: "3%",
    marginLeft: "5%",
    //color: "#FFF",
    color: "#FAEE89",
  },
  locationContainer: {
    flexDirection: "row",
  },
  headingTextBottom: {
    fontSize: 12,
    //color: "#FFFFFF",
    color: "#FAEE89",
    //fontFamily: "Sora_400Regular",
    //marginBottom: "2%",
    //marginLeft: "3%",
  },

  button: {
    marginTop: 10,
    //marginBottom: 18,
    backgroundColor: "#FDD700",
    padding: 10,
    borderRadius: 20,
    borderWidth: 2,
    width: "35%",
    alignItems: "center",
  },
  recImageBg: {
    //flex: 2,
    width: "100%",
    //height: "100%",
    //overflow: "hidden",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    height: "100%",
  },
  favButton: {
    //marginTop: 10,
    marginBottom: 18,
    backgroundColor: "#FDD700",
    //padding: 10,
    borderRadius: 20,
    borderWidth: 2,
    width: "75%",
    alignItems: "center",
    height: "20%",
    justifyContent: "center",
  },
  buttonText: {
    color: "#000000",
    fontWeight: "700",
    fontSize: 12,
  },

  searchContainer: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#313131",
    borderRadius: 15,
    width: 300,
    justifyContent: "space-around",
  },
  searchIcon: {
    width: 20,
    height: 20,
    tintColor: "#8B8C8D",
  },
  searchInput: {
    backgroundColor: "#313131",
    color: "#8B8C8D",
    width: 240,
    height: 45,
  },
  clearIcon: {
    width: "20%",
    height: "50%",
  },
  homeImage: {
    //marginBottom: "50%",
  },
});

export default styles;
